# Generated by Django 3.2.6 on 2021-08-07 07:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=django.core.files.storage.FileSystemStorage(location='/media/images')),
        ),
    ]
